/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Item;

/**
 *
 * @author Administrator
 */
public class RandomItem {

    public static final RandomCollection<Integer> ITEM_DOKHONGGIATRI = new RandomCollection<>();
    public static final RandomCollection<Integer> ITEM_DOCOGIATRI = new RandomCollection<>();
    public static final RandomCollection<Integer> ITEM_HOMMAYMAN = new RandomCollection<>();
    public static final RandomCollection<Integer> KEO_TAO = new RandomCollection<>();
    public static final RandomCollection<Integer> HOP_MA_QUY = new RandomCollection<>();
    public static final RandomCollection<Integer> DA_MA_THUAT = new RandomCollection<>();
    public static final RandomCollection<Integer> GIAY_THONG_HANH = new RandomCollection<>();
    public static final RandomCollection<Integer> BANH_KHUC_CAY_DAU_TAY = new RandomCollection<>();
    public static final RandomCollection<Integer> BANH_KHUC_CAY_CHOCOLATE = new RandomCollection<>();
    public static final RandomCollection<Integer> BANH_TET = new RandomCollection<>();
    public static final RandomCollection<Integer> BANH_CHUNG = new RandomCollection<>();
    public static final RandomCollection<Integer> TRANG_TRI = new RandomCollection<>();
    public static final RandomCollection<Integer> RANDOMFRUIT = new RandomCollection<>();
    public static final RandomCollection<Integer> DIEU_GIAY = new RandomCollection<>();
    public static final RandomCollection<Integer> DIEU_VAI = new RandomCollection<>();

    static {

        ITEM_DOKHONGGIATRI.add(20, ItemName.LANG_HON_THAO);
        ITEM_DOKHONGGIATRI.add(20, ItemName.LANG_HON_MOC);
        ITEM_DOKHONGGIATRI.add(20, ItemName.DIA_LANG_THAO);
        ITEM_DOKHONGGIATRI.add(20, ItemName.TAM_LUC_DIEP);
        ITEM_DOKHONGGIATRI.add(20, ItemName.XICH_LAN_HOA);
        ITEM_DOKHONGGIATRI.add(30, ItemName.DA_CAP_6);
        ITEM_DOKHONGGIATRI.add(20, ItemName.DA_CAP_7);
        ITEM_DOKHONGGIATRI.add(2, ItemName.DAN_CHINH_XAC);
        ITEM_DOKHONGGIATRI.add(2, ItemName.DAN_HP);
        ITEM_DOKHONGGIATRI.add(2, ItemName.DAN_TAN_CONG);
        ITEM_DOKHONGGIATRI.add(2, ItemName.DAN_KHANG);
        ITEM_DOKHONGGIATRI.add(4, ItemName.THUC_AN_6X);
        ITEM_DOKHONGGIATRI.add(4, ItemName.THUC_AN_7X);
        ITEM_DOKHONGGIATRI.add(5, ItemName.THE_BAI_KINH_NGHIEM_GIA_TOC_SO);
        ITEM_DOKHONGGIATRI.add(10, ItemName.BAO_HIEM_SO_CAP);
        ITEM_DOKHONGGIATRI.add(4, ItemName.BAO_HIEM_TRUNG_CAP);
        ITEM_DOKHONGGIATRI.add(4, ItemName.HAGGIS);
        ITEM_DOKHONGGIATRI.add(5, ItemName.DA_DANH_VONG_CAP_1);
        ITEM_DOKHONGGIATRI.add(10, ItemName.GIAY_RACH);
        ITEM_DOKHONGGIATRI.add(10, ItemName.GIAY_BAC);
        ITEM_DOKHONGGIATRI.add(0.1, ItemName.DA_THANG_AN);
        ITEM_DOKHONGGIATRI.add(0.1, ItemName.HOA_TUYET);
        ITEM_DOKHONGGIATRI.add(0.1, ItemName.NHAM_THACH);
        ITEM_DOKHONGGIATRI.add(0.1, ItemName.PHA_LE);
        //////////////
        
        
        
        
        
        
        
        

        ITEM_DOCOGIATRI.add(20, ItemName.LANG_HON_THAO);
        ITEM_DOCOGIATRI.add(20, ItemName.LANG_HON_MOC);
        ITEM_DOCOGIATRI.add(20, ItemName.DIA_LANG_THAO);
        ITEM_DOCOGIATRI.add(20, ItemName.TAM_LUC_DIEP);
        ITEM_DOCOGIATRI.add(20, ItemName.XICH_LAN_HOA);
        ITEM_DOCOGIATRI.add(5, ItemName.DA_CAP_8);
        ITEM_DOCOGIATRI.add(5, ItemName.DA_CAP_9);

        ITEM_DOCOGIATRI.add(5, ItemName.BAO_HIEM_SO_CAP);
        ITEM_DOCOGIATRI.add(3, ItemName.BAO_HIEM_TRUNG_CAP);
        ITEM_DOCOGIATRI.add(1, ItemName.BAO_HIEM_CAO_CAP);

        ITEM_DOCOGIATRI.add(3, ItemName.THUC_AN_6X);
        ITEM_DOCOGIATRI.add(2, ItemName.THUC_AN_7X);
        ITEM_DOCOGIATRI.add(1, ItemName.HAGGIS);

        ITEM_DOCOGIATRI.add(1, ItemName.DAN_HP);
        ITEM_DOCOGIATRI.add(1, ItemName.DAN_TAN_CONG);
        ITEM_DOCOGIATRI.add(2, ItemName.DAN_KHANG);
        ITEM_DOCOGIATRI.add(2, ItemName.DAN_CHINH_XAC);

        ITEM_DOCOGIATRI.add(5, ItemName.THE_BAI_KINH_NGHIEM_GIA_TOC_SO);
        ITEM_DOCOGIATRI.add(3, ItemName.THE_BAI_KINH_NGHIEM_GIA_TOC_TRUNG);
        ITEM_DOCOGIATRI.add(1, ItemName.THE_BAI_KINH_NGHIEM_GIA_TOC_CAO);
        ITEM_DOCOGIATRI.add(5, ItemName.EXP_TRAU);
        ITEM_DOCOGIATRI.add(5, ItemName.LUC_THANH_HOA);
        ITEM_DOCOGIATRI.add(5, ItemName.TU_LINH_LIEN_HOA);
        ITEM_DOCOGIATRI.add(5, ItemName.BANH_RANG);
        ITEM_DOCOGIATRI.add(5, ItemName.IK);

        ITEM_DOCOGIATRI.add(1, ItemName.MANH_GIAY_VUN);
        ITEM_DOCOGIATRI.add(1, ItemName.TU_TINH_THACH_SO_CAP);
        ITEM_DOCOGIATRI.add(5, ItemName.DA_DANH_VONG_CAP_1);
        ITEM_DOCOGIATRI.add(4, ItemName.DA_DANH_VONG_CAP_2);

        ITEM_DOCOGIATRI.add(1, ItemName.DA_THANG_AN);
        ITEM_DOCOGIATRI.add(1, ItemName.HOA_TUYET);
        ITEM_DOCOGIATRI.add(1, ItemName.NHAM_THACH);
        ITEM_DOCOGIATRI.add(1, ItemName.PHA_LE);

        ITEM_DOCOGIATRI.add(0.01, ItemName.CHUYEN_TINH_THACH);
        ITEM_DOCOGIATRI.add(1, ItemName.BI_KIP_CUNG);
        ITEM_DOCOGIATRI.add(1, ItemName.BI_KIP_DAO);
        ITEM_DOCOGIATRI.add(1, ItemName.BI_KIP_KIEM_THUAT);
        ITEM_DOCOGIATRI.add(1, ItemName.BI_KIP_TIEU_THUAT);
        ITEM_DOCOGIATRI.add(1, ItemName.BI_KIP_QUAT);
        ITEM_DOCOGIATRI.add(1, ItemName.BI_KIP_KUNAI);

        ITEM_DOCOGIATRI.add(0.1, ItemName.PET_BONG_MA);
        ITEM_DOCOGIATRI.add(0.1, ItemName.PET_YEU_TINH);
        ITEM_DOCOGIATRI.add(0.1, ItemName.GAY_MAT_TRANG);
        ITEM_DOCOGIATRI.add(0.1, ItemName.GAY_TRAI_TIM);
        ITEM_DOCOGIATRI.add(0.1, ItemName.HAKAIRO_YOROI);
        ITEM_DOCOGIATRI.add(0.1, ItemName.MAT_NA_HO);
        ITEM_DOCOGIATRI.add(0.1, ItemName.MAT_NA_HO_1);
        ITEM_DOCOGIATRI.add(0.1, ItemName.NHAT_TU_LAM_PHONG);
        ITEM_DOCOGIATRI.add(0.1, ItemName.THIEN_NGUYET_CHI_NU);

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        ITEM_HOMMAYMAN.add(20, ItemName.MAT_NA_HO);
        ITEM_HOMMAYMAN.add(20, ItemName.MAT_NA_HO_1);
        ITEM_HOMMAYMAN.add(20, ItemName.SHIRAIJI);
        ITEM_HOMMAYMAN.add(20, ItemName.HAJIRO);
        ITEM_HOMMAYMAN.add(20, ItemName.GAY_MAT_TRANG);
        ITEM_HOMMAYMAN.add(20, ItemName.GAY_TRAI_TIM);
        ITEM_HOMMAYMAN.add(20, ItemName.PET_YEU_TINH);
        ITEM_HOMMAYMAN.add(20, ItemName.PET_BONG_MA);
        //
        KEO_TAO.add(25, ItemName.DA_CAP_5);
        KEO_TAO.add(20, ItemName.DA_CAP_6);
        KEO_TAO.add(15, ItemName.DA_CAP_7);
        KEO_TAO.add(5, ItemName.THE_BAI_KINH_NGHIEM_GIA_TOC_SO);
        KEO_TAO.add(5, ItemName.THE_BAI_KINH_NGHIEM_GIA_TOC_TRUNG);
        KEO_TAO.add(4, ItemName.SASHIMI_CAO_CAP);
        KEO_TAO.add(4, ItemName.THUC_AN_6X);
        KEO_TAO.add(10, ItemName.DAN_CHINH_XAC);
        KEO_TAO.add(10, ItemName.DAN_HP);
        KEO_TAO.add(10, ItemName.DAN_TAN_CONG);
        KEO_TAO.add(10, ItemName.DAN_KHANG);
        KEO_TAO.add(5, ItemName.DOI_DEN);
        KEO_TAO.add(5, ItemName.HOA_TUYET);
        KEO_TAO.add(1, ItemName.BAT_BAO);
        KEO_TAO.add(4, ItemName.HAC_NGUU);
        KEO_TAO.add(5, ItemName.EXP_TRAU);
        KEO_TAO.add(4, ItemName.HOAN_COT_CHI_CHU_SO_CAP);
        KEO_TAO.add(4, ItemName.MAT_NA_VEGETA);
        KEO_TAO.add(4, ItemName.MAT_NA_KUNOICHI);
        KEO_TAO.add(5, ItemName.DA_DANH_VONG_CAP_1);
        KEO_TAO.add(5, ItemName.DA_DANH_VONG_CAP_2);
        KEO_TAO.add(10, ItemName.HOAN_LUONG_CHI_THAO);
        KEO_TAO.add(10, ItemName.HOAN_CHUYEN_SO_CAP);
//        KEO_TAO.add(10, ItemName.MAT_NA_THO);
//        KEO_TAO.add(10, ItemName.MAT_NA_THO_1);
        KEO_TAO.add(1, ItemName.PHA_LE);
        KEO_TAO.add(1, ItemName.NHAM_THACH);
        KEO_TAO.add(2, ItemName.UNG_LONG);
        ///
        HOP_MA_QUY.add(2, ItemName.MANH_AO_JIRAI);
        HOP_MA_QUY.add(2, ItemName.MANH_QUAN_JIRAI);
        HOP_MA_QUY.add(2, ItemName.MANH_GANG_TAY_JIRAI);
        HOP_MA_QUY.add(2, ItemName.MANH_GIAY_JIRAI);
        HOP_MA_QUY.add(2, ItemName.MANH_NON_JIRAI);
        HOP_MA_QUY.add(2, ItemName.MANH_NGOC_BOI_JIRAI);
        HOP_MA_QUY.add(2, ItemName.MANH_NHAN_JIRAI);
        HOP_MA_QUY.add(2, ItemName.MANH_PHU_JIRAI);
        HOP_MA_QUY.add(2, ItemName.MANH_DAY_CHUYEN_JIRAI);
        HOP_MA_QUY.add(2, ItemName.MANH_AO_JUMITO);
        HOP_MA_QUY.add(2, ItemName.MANH_QUAN_JUMITO);
        HOP_MA_QUY.add(2, ItemName.MANH_GANG_TAY_JUMITO);
        HOP_MA_QUY.add(2, ItemName.MANH_GIAY_JUMITO);
        HOP_MA_QUY.add(2, ItemName.MANH_NON_JUMITO);
        HOP_MA_QUY.add(2, ItemName.MANH_NGOC_BOI_JUMITO);
        HOP_MA_QUY.add(2, ItemName.MANH_NHAN_JUMITO);
        HOP_MA_QUY.add(2, ItemName.MANH_PHU_JUMITO);
        HOP_MA_QUY.add(2, ItemName.MANH_DAY_CHUYEN_JUMITO);
        HOP_MA_QUY.add(10, ItemName.DA_CAP_6);
        HOP_MA_QUY.add(10, ItemName.DA_CAP_7);
        HOP_MA_QUY.add(10, ItemName.DA_CAP_8);
        HOP_MA_QUY.add(10, ItemName.DA_CAP_9);
        HOP_MA_QUY.add(10, ItemName.DA_CAP_10);
        HOP_MA_QUY.add(10, ItemName.DA_CAP_11);
        HOP_MA_QUY.add(7, ItemName.DAN_CHINH_XAC);
        HOP_MA_QUY.add(7, ItemName.DAN_HP);
        HOP_MA_QUY.add(7, ItemName.DAN_TAN_CONG);
        HOP_MA_QUY.add(7, ItemName.DAN_KHANG);
        HOP_MA_QUY.add(1, ItemName.BAT_BAO);
        HOP_MA_QUY.add(2, ItemName.CHIM_TINH_ANH);
        HOP_MA_QUY.add(0.50, ItemName.RUONG_BACH_NGAN);
        HOP_MA_QUY.add(0.25, ItemName.RUONG_HUYEN_BI);
        HOP_MA_QUY.add(3, ItemName.TUONG_LINH_THAO);
        HOP_MA_QUY.add(3, ItemName.HAC_NGUU);
        HOP_MA_QUY.add(3, ItemName.XICH_NHAN_NGAN_LANG);
        HOP_MA_QUY.add(2, ItemName.MAT_NA_ONNA_BUGEISHA);
        HOP_MA_QUY.add(2, ItemName.MAT_NA_SUPER_BROLY);
        HOP_MA_QUY.add(0.5, ItemName.BO_CAI_THIEN_GIAM_XOC);
        HOP_MA_QUY.add(0.5, ItemName.BO_CAI_THIEN_DANH_LUA);
        HOP_MA_QUY.add(0.5, ItemName.BO_CAI_THIEN_DONG_CO);
        HOP_MA_QUY.add(4, ItemName.HOAN_COT_CHI_CHU_TRUNG_CAP);
        HOP_MA_QUY.add(4, ItemName.HOAN_COT_CHI_CHU_CAO_CAP);
        HOP_MA_QUY.add(4, ItemName.HOAN_LUONG_CHI_THAO);
        HOP_MA_QUY.add(3, ItemName.TUI_VAI_CAP_3);
        HOP_MA_QUY.add(1, ItemName.HOA_TUYET);
        HOP_MA_QUY.add(1, ItemName.PHA_LE);
        HOP_MA_QUY.add(1, ItemName.NHAM_THACH);
        HOP_MA_QUY.add(2, ItemName.THUC_AN_7X);
        HOP_MA_QUY.add(1, ItemName.HAGGIS);
        HOP_MA_QUY.add(1, ItemName.GAY_TRAI_TIM);
        HOP_MA_QUY.add(1, ItemName.GAY_MAT_TRANG);
        HOP_MA_QUY.add(1, ItemName.HOAN_CHUYEN_TRUNG_CAP);
        HOP_MA_QUY.add(1, ItemName.HOAN_CHUYEN_SO_CAP);
        HOP_MA_QUY.add(0.5, ItemName.HARLEY_DAVIDSON);
        HOP_MA_QUY.add(0.5, ItemName.XE_MAY);
        HOP_MA_QUY.add(0.5, ItemName.NHAT_TU_LAM_PHONG);
        HOP_MA_QUY.add(0.5, ItemName.THIEN_NGUYET_CHI_NU);
        HOP_MA_QUY.add(0.5, ItemName.MAT_NA_SHIN_AH);
        HOP_MA_QUY.add(0.5, ItemName.MAT_NA_VO_DIEN);
        HOP_MA_QUY.add(0.5, ItemName.MAT_NA_ONI);
        HOP_MA_QUY.add(0.5, ItemName.MAT_NA_KUMA);
        HOP_MA_QUY.add(0.5, ItemName.MAT_NA_INU);
        //
        GIAY_THONG_HANH.add(25, ItemName.DA_CAP_5);
        GIAY_THONG_HANH.add(20, ItemName.DA_CAP_6);
        GIAY_THONG_HANH.add(15, ItemName.DA_CAP_7);
        GIAY_THONG_HANH.add(5, ItemName.THE_BAI_KINH_NGHIEM_GIA_TOC_SO);
        GIAY_THONG_HANH.add(5, ItemName.THE_BAI_KINH_NGHIEM_GIA_TOC_TRUNG);
        GIAY_THONG_HANH.add(4, ItemName.SASHIMI_CAO_CAP);
        GIAY_THONG_HANH.add(4, ItemName.THUC_AN_6X);
        GIAY_THONG_HANH.add(10, ItemName.DAN_CHINH_XAC);
        GIAY_THONG_HANH.add(10, ItemName.DAN_HP);
        GIAY_THONG_HANH.add(10, ItemName.DAN_TAN_CONG);
        GIAY_THONG_HANH.add(10, ItemName.DAN_KHANG);
        GIAY_THONG_HANH.add(5, ItemName.DOI_DEN);
        GIAY_THONG_HANH.add(5, ItemName.HOA_TUYET);
        GIAY_THONG_HANH.add(1, ItemName.BAT_BAO);
        GIAY_THONG_HANH.add(4, ItemName.HAC_NGUU);
        GIAY_THONG_HANH.add(5, ItemName.EXP_TRAU);
        GIAY_THONG_HANH.add(4, ItemName.HOAN_COT_CHI_CHU_SO_CAP);
        GIAY_THONG_HANH.add(4, ItemName.MAT_NA_VEGETA);
        GIAY_THONG_HANH.add(4, ItemName.MAT_NA_KUNOICHI);
        GIAY_THONG_HANH.add(5, ItemName.DA_DANH_VONG_CAP_1);
        GIAY_THONG_HANH.add(5, ItemName.DA_DANH_VONG_CAP_2);
        GIAY_THONG_HANH.add(10, ItemName.HOAN_LUONG_CHI_THAO);
        GIAY_THONG_HANH.add(10, ItemName.HOAN_CHUYEN_SO_CAP);
        GIAY_THONG_HANH.add(1, ItemName.PHA_LE);
        GIAY_THONG_HANH.add(1, ItemName.NHAM_THACH);
        GIAY_THONG_HANH.add(2, ItemName.UNG_LONG);
        ///
        DA_MA_THUAT.add(2, ItemName.MANH_AO_JIRAI);
        DA_MA_THUAT.add(2, ItemName.MANH_QUAN_JIRAI);
        DA_MA_THUAT.add(2, ItemName.MANH_GANG_TAY_JIRAI);
        DA_MA_THUAT.add(2, ItemName.MANH_GIAY_JIRAI);
        DA_MA_THUAT.add(2, ItemName.MANH_NON_JIRAI);
        DA_MA_THUAT.add(2, ItemName.MANH_NGOC_BOI_JIRAI);
        DA_MA_THUAT.add(2, ItemName.MANH_NHAN_JIRAI);
        DA_MA_THUAT.add(2, ItemName.MANH_PHU_JIRAI);
        DA_MA_THUAT.add(2, ItemName.MANH_DAY_CHUYEN_JIRAI);
        DA_MA_THUAT.add(2, ItemName.MANH_AO_JUMITO);
        DA_MA_THUAT.add(2, ItemName.MANH_QUAN_JUMITO);
        DA_MA_THUAT.add(2, ItemName.MANH_GANG_TAY_JUMITO);
        DA_MA_THUAT.add(2, ItemName.MANH_GIAY_JUMITO);
        DA_MA_THUAT.add(2, ItemName.MANH_NON_JUMITO);
        DA_MA_THUAT.add(2, ItemName.MANH_NGOC_BOI_JUMITO);
        DA_MA_THUAT.add(2, ItemName.MANH_NHAN_JUMITO);
        DA_MA_THUAT.add(2, ItemName.MANH_PHU_JUMITO);
        DA_MA_THUAT.add(2, ItemName.MANH_DAY_CHUYEN_JUMITO);
        DA_MA_THUAT.add(10, ItemName.DA_CAP_6);
        DA_MA_THUAT.add(10, ItemName.DA_CAP_7);
        DA_MA_THUAT.add(10, ItemName.DA_CAP_8);
        DA_MA_THUAT.add(10, ItemName.DA_CAP_9);
        DA_MA_THUAT.add(10, ItemName.DA_CAP_10);
        DA_MA_THUAT.add(10, ItemName.DA_CAP_11);
        DA_MA_THUAT.add(7, ItemName.DAN_CHINH_XAC);
        DA_MA_THUAT.add(7, ItemName.DAN_HP);
        DA_MA_THUAT.add(7, ItemName.DAN_TAN_CONG);
        DA_MA_THUAT.add(7, ItemName.DAN_KHANG);
        DA_MA_THUAT.add(1, ItemName.BAT_BAO);
        DA_MA_THUAT.add(2, ItemName.CHIM_TINH_ANH);
        DA_MA_THUAT.add(0.50, ItemName.RUONG_BACH_NGAN);
        DA_MA_THUAT.add(0.25, ItemName.RUONG_HUYEN_BI);
        DA_MA_THUAT.add(3, ItemName.TUONG_LINH_THAO);
        DA_MA_THUAT.add(3, ItemName.HAC_NGUU);
        DA_MA_THUAT.add(3, ItemName.XICH_NHAN_NGAN_LANG);
        DA_MA_THUAT.add(2, ItemName.MAT_NA_ONNA_BUGEISHA);
        DA_MA_THUAT.add(2, ItemName.MAT_NA_SUPER_BROLY);
        DA_MA_THUAT.add(0.5, ItemName.BO_CAI_THIEN_GIAM_XOC);
        DA_MA_THUAT.add(0.5, ItemName.BO_CAI_THIEN_DANH_LUA);
        DA_MA_THUAT.add(0.5, ItemName.BO_CAI_THIEN_DONG_CO);
        DA_MA_THUAT.add(4, ItemName.HOAN_COT_CHI_CHU_TRUNG_CAP);
        DA_MA_THUAT.add(4, ItemName.HOAN_COT_CHI_CHU_CAO_CAP);
        DA_MA_THUAT.add(4, ItemName.HOAN_LUONG_CHI_THAO);
        DA_MA_THUAT.add(3, ItemName.TUI_VAI_CAP_3);
        DA_MA_THUAT.add(1, ItemName.HOA_TUYET);
        DA_MA_THUAT.add(1, ItemName.PHA_LE);
        DA_MA_THUAT.add(1, ItemName.NHAM_THACH);
        DA_MA_THUAT.add(2, ItemName.THUC_AN_7X);
        DA_MA_THUAT.add(1, ItemName.HAGGIS);
        DA_MA_THUAT.add(1, ItemName.GAY_TRAI_TIM);
        DA_MA_THUAT.add(1, ItemName.GAY_MAT_TRANG);
        DA_MA_THUAT.add(1, ItemName.HOAN_CHUYEN_TRUNG_CAP);
        DA_MA_THUAT.add(1, ItemName.HOAN_CHUYEN_SO_CAP);
        DA_MA_THUAT.add(0.5, ItemName.HARLEY_DAVIDSON);
        DA_MA_THUAT.add(0.5, ItemName.XE_MAY);
        DA_MA_THUAT.add(0.5, ItemName.NHAT_TU_LAM_PHONG);
        DA_MA_THUAT.add(0.5, ItemName.THIEN_NGUYET_CHI_NU);
        DA_MA_THUAT.add(0.5, ItemName.MAT_NA_SHIN_AH);
        DA_MA_THUAT.add(0.5, ItemName.MAT_NA_VO_DIEN);
        DA_MA_THUAT.add(0.5, ItemName.MAT_NA_ONI);
        DA_MA_THUAT.add(0.5, ItemName.MAT_NA_KUMA);
        DA_MA_THUAT.add(0.5, ItemName.MAT_NA_INU);
        
        //
        BANH_KHUC_CAY_DAU_TAY.add(25, ItemName.DA_CAP_5);
        BANH_KHUC_CAY_DAU_TAY.add(20, ItemName.DA_CAP_6);
        BANH_KHUC_CAY_DAU_TAY.add(15, ItemName.DA_CAP_7);
        BANH_KHUC_CAY_DAU_TAY.add(5, ItemName.THE_BAI_KINH_NGHIEM_GIA_TOC_SO);
        BANH_KHUC_CAY_DAU_TAY.add(5, ItemName.THE_BAI_KINH_NGHIEM_GIA_TOC_TRUNG);
        BANH_KHUC_CAY_DAU_TAY.add(4, ItemName.SASHIMI_CAO_CAP);
        BANH_KHUC_CAY_DAU_TAY.add(4, ItemName.THUC_AN_6X);
        BANH_KHUC_CAY_DAU_TAY.add(10, ItemName.DAN_CHINH_XAC);
        BANH_KHUC_CAY_DAU_TAY.add(10, ItemName.DAN_HP);
        BANH_KHUC_CAY_DAU_TAY.add(10, ItemName.DAN_TAN_CONG);
        BANH_KHUC_CAY_DAU_TAY.add(10, ItemName.DAN_KHANG);
        BANH_KHUC_CAY_DAU_TAY.add(5, ItemName.DOI_DEN);
        BANH_KHUC_CAY_DAU_TAY.add(5, ItemName.HOA_TUYET);
        BANH_KHUC_CAY_DAU_TAY.add(1, ItemName.BAT_BAO);
        BANH_KHUC_CAY_DAU_TAY.add(4, ItemName.HAC_NGUU);
        BANH_KHUC_CAY_DAU_TAY.add(5, ItemName.EXP_TRAU);
        BANH_KHUC_CAY_DAU_TAY.add(4, ItemName.HOAN_COT_CHI_CHU_SO_CAP);
        BANH_KHUC_CAY_DAU_TAY.add(4, ItemName.MAT_NA_VEGETA);
        BANH_KHUC_CAY_DAU_TAY.add(4, ItemName.MAT_NA_KUNOICHI);
        BANH_KHUC_CAY_DAU_TAY.add(5, ItemName.DA_DANH_VONG_CAP_1);
        BANH_KHUC_CAY_DAU_TAY.add(5, ItemName.DA_DANH_VONG_CAP_2);
        BANH_KHUC_CAY_DAU_TAY.add(10, ItemName.HOAN_LUONG_CHI_THAO);
        BANH_KHUC_CAY_DAU_TAY.add(10, ItemName.HOAN_CHUYEN_SO_CAP);
        BANH_KHUC_CAY_DAU_TAY.add(1, ItemName.PHA_LE);
        BANH_KHUC_CAY_DAU_TAY.add(1, ItemName.NHAM_THACH);
        BANH_KHUC_CAY_DAU_TAY.add(2, ItemName.UNG_LONG);
        ///
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MANH_AO_JIRAI);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MANH_QUAN_JIRAI);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MANH_GANG_TAY_JIRAI);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MANH_GIAY_JIRAI);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MANH_NON_JIRAI);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MANH_NGOC_BOI_JIRAI);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MANH_NHAN_JIRAI);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MANH_PHU_JIRAI);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MANH_DAY_CHUYEN_JIRAI);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MANH_AO_JUMITO);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MANH_QUAN_JUMITO);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MANH_GANG_TAY_JUMITO);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MANH_GIAY_JUMITO);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MANH_NON_JUMITO);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MANH_NGOC_BOI_JUMITO);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MANH_NHAN_JUMITO);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MANH_PHU_JUMITO);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MANH_DAY_CHUYEN_JUMITO);
        BANH_KHUC_CAY_CHOCOLATE.add(10, ItemName.DA_CAP_6);
        BANH_KHUC_CAY_CHOCOLATE.add(10, ItemName.DA_CAP_7);
        BANH_KHUC_CAY_CHOCOLATE.add(10, ItemName.DA_CAP_8);
        BANH_KHUC_CAY_CHOCOLATE.add(10, ItemName.DA_CAP_9);
        BANH_KHUC_CAY_CHOCOLATE.add(10, ItemName.DA_CAP_10);
        BANH_KHUC_CAY_CHOCOLATE.add(10, ItemName.DA_CAP_11);
        BANH_KHUC_CAY_CHOCOLATE.add(7, ItemName.DAN_CHINH_XAC);
        BANH_KHUC_CAY_CHOCOLATE.add(7, ItemName.DAN_HP);
        BANH_KHUC_CAY_CHOCOLATE.add(7, ItemName.DAN_TAN_CONG);
        BANH_KHUC_CAY_CHOCOLATE.add(7, ItemName.DAN_KHANG);
        BANH_KHUC_CAY_CHOCOLATE.add(1, ItemName.BAT_BAO);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.CHIM_TINH_ANH);
        BANH_KHUC_CAY_CHOCOLATE.add(0.50, ItemName.RUONG_BACH_NGAN);
        BANH_KHUC_CAY_CHOCOLATE.add(0.25, ItemName.RUONG_HUYEN_BI);
        BANH_KHUC_CAY_CHOCOLATE.add(3, ItemName.TUONG_LINH_THAO);
        BANH_KHUC_CAY_CHOCOLATE.add(3, ItemName.HAC_NGUU);
        BANH_KHUC_CAY_CHOCOLATE.add(3, ItemName.XICH_NHAN_NGAN_LANG);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MAT_NA_ONNA_BUGEISHA);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.MAT_NA_SUPER_BROLY);
        BANH_KHUC_CAY_CHOCOLATE.add(0.5, ItemName.BO_CAI_THIEN_GIAM_XOC);
        BANH_KHUC_CAY_CHOCOLATE.add(0.5, ItemName.BO_CAI_THIEN_DANH_LUA);
        BANH_KHUC_CAY_CHOCOLATE.add(0.5, ItemName.BO_CAI_THIEN_DONG_CO);
        BANH_KHUC_CAY_CHOCOLATE.add(4, ItemName.HOAN_COT_CHI_CHU_TRUNG_CAP);
        BANH_KHUC_CAY_CHOCOLATE.add(4, ItemName.HOAN_COT_CHI_CHU_CAO_CAP);
        BANH_KHUC_CAY_CHOCOLATE.add(4, ItemName.HOAN_LUONG_CHI_THAO);
        BANH_KHUC_CAY_CHOCOLATE.add(3, ItemName.TUI_VAI_CAP_3);
        BANH_KHUC_CAY_CHOCOLATE.add(1, ItemName.HOA_TUYET);
        BANH_KHUC_CAY_CHOCOLATE.add(1, ItemName.PHA_LE);
        BANH_KHUC_CAY_CHOCOLATE.add(1, ItemName.NHAM_THACH);
        BANH_KHUC_CAY_CHOCOLATE.add(2, ItemName.THUC_AN_7X);
        BANH_KHUC_CAY_CHOCOLATE.add(1, ItemName.HAGGIS);
        BANH_KHUC_CAY_CHOCOLATE.add(1, ItemName.GAY_TRAI_TIM);
        BANH_KHUC_CAY_CHOCOLATE.add(1, ItemName.GAY_MAT_TRANG);
        BANH_KHUC_CAY_CHOCOLATE.add(1, ItemName.HOAN_CHUYEN_TRUNG_CAP);
        BANH_KHUC_CAY_CHOCOLATE.add(1, ItemName.HOAN_CHUYEN_SO_CAP);
        BANH_KHUC_CAY_CHOCOLATE.add(0.5, ItemName.HARLEY_DAVIDSON);
        BANH_KHUC_CAY_CHOCOLATE.add(0.5, ItemName.XE_MAY);
        BANH_KHUC_CAY_CHOCOLATE.add(0.5, ItemName.NHAT_TU_LAM_PHONG);
        BANH_KHUC_CAY_CHOCOLATE.add(0.5, ItemName.THIEN_NGUYET_CHI_NU);
        BANH_KHUC_CAY_CHOCOLATE.add(0.5, ItemName.MAT_NA_SHIN_AH);
        BANH_KHUC_CAY_CHOCOLATE.add(0.5, ItemName.MAT_NA_VO_DIEN);
        BANH_KHUC_CAY_CHOCOLATE.add(0.5, ItemName.MAT_NA_ONI);
        BANH_KHUC_CAY_CHOCOLATE.add(0.5, ItemName.MAT_NA_KUMA);
        BANH_KHUC_CAY_CHOCOLATE.add(0.5, ItemName.MAT_NA_INU);
        //
        BANH_TET.add(25, ItemName.DA_CAP_5);
        BANH_TET.add(20, ItemName.DA_CAP_6);
        BANH_TET.add(15, ItemName.DA_CAP_7);
        BANH_TET.add(5, ItemName.THE_BAI_KINH_NGHIEM_GIA_TOC_SO);
        BANH_TET.add(5, ItemName.THE_BAI_KINH_NGHIEM_GIA_TOC_TRUNG);
        BANH_TET.add(4, ItemName.SASHIMI_CAO_CAP);
        BANH_TET.add(4, ItemName.THUC_AN_6X);
        BANH_TET.add(10, ItemName.DAN_CHINH_XAC);
        BANH_TET.add(10, ItemName.DAN_HP);
        BANH_TET.add(10, ItemName.DAN_TAN_CONG);
        BANH_TET.add(10, ItemName.DAN_KHANG);
        BANH_TET.add(5, ItemName.DOI_DEN);
        BANH_TET.add(5, ItemName.HOA_TUYET);
        BANH_TET.add(1, ItemName.BAT_BAO);
        BANH_TET.add(4, ItemName.HAC_NGUU);
        BANH_TET.add(5, ItemName.EXP_TRAU);
        BANH_TET.add(4, ItemName.HOAN_COT_CHI_CHU_SO_CAP);
        BANH_TET.add(4, ItemName.MAT_NA_VEGETA);
        BANH_TET.add(4, ItemName.MAT_NA_KUNOICHI);
        BANH_TET.add(5, ItemName.DA_DANH_VONG_CAP_1);
        BANH_TET.add(5, ItemName.DA_DANH_VONG_CAP_2);
        BANH_TET.add(10, ItemName.HOAN_LUONG_CHI_THAO);
        BANH_TET.add(10, ItemName.HOAN_CHUYEN_SO_CAP);
        BANH_TET.add(1, ItemName.PHA_LE);
        BANH_TET.add(1, ItemName.NHAM_THACH);
        BANH_TET.add(2, ItemName.UNG_LONG);
        ///
        BANH_CHUNG.add(2, ItemName.MANH_AO_JIRAI);
        BANH_CHUNG.add(2, ItemName.MANH_QUAN_JIRAI);
        BANH_CHUNG.add(2, ItemName.MANH_GANG_TAY_JIRAI);
        BANH_CHUNG.add(2, ItemName.MANH_GIAY_JIRAI);
        BANH_CHUNG.add(2, ItemName.MANH_NON_JIRAI);
        BANH_CHUNG.add(2, ItemName.MANH_NGOC_BOI_JIRAI);
        BANH_CHUNG.add(2, ItemName.MANH_NHAN_JIRAI);
        BANH_CHUNG.add(2, ItemName.MANH_PHU_JIRAI);
        BANH_CHUNG.add(2, ItemName.MANH_DAY_CHUYEN_JIRAI);
        BANH_CHUNG.add(2, ItemName.MANH_AO_JUMITO);
        BANH_CHUNG.add(2, ItemName.MANH_QUAN_JUMITO);
        BANH_CHUNG.add(2, ItemName.MANH_GANG_TAY_JUMITO);
        BANH_CHUNG.add(2, ItemName.MANH_GIAY_JUMITO);
        BANH_CHUNG.add(2, ItemName.MANH_NON_JUMITO);
        BANH_CHUNG.add(2, ItemName.MANH_NGOC_BOI_JUMITO);
        BANH_CHUNG.add(2, ItemName.MANH_NHAN_JUMITO);
        BANH_CHUNG.add(2, ItemName.MANH_PHU_JUMITO);
        BANH_CHUNG.add(2, ItemName.MANH_DAY_CHUYEN_JUMITO);
        BANH_CHUNG.add(10, ItemName.DA_CAP_6);
        BANH_CHUNG.add(10, ItemName.DA_CAP_7);
        BANH_CHUNG.add(10, ItemName.DA_CAP_8);
        BANH_CHUNG.add(10, ItemName.DA_CAP_9);
        BANH_CHUNG.add(10, ItemName.DA_CAP_10);
        BANH_CHUNG.add(10, ItemName.DA_CAP_11);
        BANH_CHUNG.add(7, ItemName.DAN_CHINH_XAC);
        BANH_CHUNG.add(7, ItemName.DAN_HP);
        BANH_CHUNG.add(7, ItemName.DAN_TAN_CONG);
        BANH_CHUNG.add(7, ItemName.DAN_KHANG);
        BANH_CHUNG.add(1, ItemName.BAT_BAO);
        BANH_CHUNG.add(2, ItemName.CHIM_TINH_ANH);
        BANH_CHUNG.add(0.50, ItemName.RUONG_BACH_NGAN);
        BANH_CHUNG.add(0.25, ItemName.RUONG_HUYEN_BI);
        BANH_CHUNG.add(3, ItemName.TUONG_LINH_THAO);
        BANH_CHUNG.add(3, ItemName.HAC_NGUU);
        BANH_CHUNG.add(3, ItemName.XICH_NHAN_NGAN_LANG);
        BANH_CHUNG.add(2, ItemName.MAT_NA_ONNA_BUGEISHA);
        BANH_CHUNG.add(2, ItemName.MAT_NA_SUPER_BROLY);
        BANH_CHUNG.add(0.5, ItemName.BO_CAI_THIEN_GIAM_XOC);
        BANH_CHUNG.add(0.5, ItemName.BO_CAI_THIEN_DANH_LUA);
        BANH_CHUNG.add(0.5, ItemName.BO_CAI_THIEN_DONG_CO);
        BANH_CHUNG.add(4, ItemName.HOAN_COT_CHI_CHU_TRUNG_CAP);
        BANH_CHUNG.add(4, ItemName.HOAN_COT_CHI_CHU_CAO_CAP);
        BANH_CHUNG.add(4, ItemName.HOAN_LUONG_CHI_THAO);
        BANH_CHUNG.add(3, ItemName.TUI_VAI_CAP_3);
        BANH_CHUNG.add(1, ItemName.HOA_TUYET);
        BANH_CHUNG.add(1, ItemName.PHA_LE);
        BANH_CHUNG.add(1, ItemName.NHAM_THACH);
        BANH_CHUNG.add(2, ItemName.THUC_AN_7X);
        BANH_CHUNG.add(1, ItemName.HAGGIS);
        BANH_CHUNG.add(1, ItemName.GAY_TRAI_TIM);
        BANH_CHUNG.add(1, ItemName.GAY_MAT_TRANG);
        BANH_CHUNG.add(1, ItemName.HOAN_CHUYEN_TRUNG_CAP);
        BANH_CHUNG.add(1, ItemName.HOAN_CHUYEN_SO_CAP);
        BANH_CHUNG.add(0.5, ItemName.HARLEY_DAVIDSON);
        BANH_CHUNG.add(0.5, ItemName.XE_MAY);
        BANH_CHUNG.add(0.5, ItemName.NHAT_TU_LAM_PHONG);
        BANH_CHUNG.add(0.5, ItemName.THIEN_NGUYET_CHI_NU);
        BANH_CHUNG.add(0.5, ItemName.MAT_NA_SHIN_AH);
        BANH_CHUNG.add(0.5, ItemName.MAT_NA_VO_DIEN);
        BANH_CHUNG.add(0.5, ItemName.MAT_NA_ONI);
        BANH_CHUNG.add(0.5, ItemName.MAT_NA_KUMA);
        BANH_CHUNG.add(0.5, ItemName.MAT_NA_INU);
        BANH_CHUNG.add(0.5, ItemName.HOA_KY_LAN);
        BANH_CHUNG.add(0.5, ItemName.PHUONG_HOANG_NEW);
        BANH_CHUNG.add(0.5, ItemName.AO_DAI_NAM);
        BANH_CHUNG.add(0.5, ItemName.AO_DAI_NU);
        BANH_CHUNG.add(0.01, ItemName.BUA_AITEMU);
        BANH_CHUNG.add(0.01, ItemName.BUA_NORU);
        BANH_CHUNG.add(0.01, ItemName.BUA_SOCHI);
        //
        TRANG_TRI.add(2, ItemName.MANH_AO_JIRAI);
        TRANG_TRI.add(2, ItemName.MANH_QUAN_JIRAI);
        TRANG_TRI.add(2, ItemName.MANH_GANG_TAY_JIRAI);
        TRANG_TRI.add(2, ItemName.MANH_GIAY_JIRAI);
        TRANG_TRI.add(2, ItemName.MANH_NON_JIRAI);
        TRANG_TRI.add(2, ItemName.MANH_NGOC_BOI_JIRAI);
        TRANG_TRI.add(2, ItemName.MANH_NHAN_JIRAI);
        TRANG_TRI.add(2, ItemName.MANH_PHU_JIRAI);
        TRANG_TRI.add(2, ItemName.MANH_DAY_CHUYEN_JIRAI);
        TRANG_TRI.add(2, ItemName.MANH_AO_JUMITO);
        TRANG_TRI.add(2, ItemName.MANH_QUAN_JUMITO);
        TRANG_TRI.add(2, ItemName.MANH_GANG_TAY_JUMITO);
        TRANG_TRI.add(2, ItemName.MANH_GIAY_JUMITO);
        TRANG_TRI.add(2, ItemName.MANH_NON_JUMITO);
        TRANG_TRI.add(2, ItemName.MANH_NGOC_BOI_JUMITO);
        TRANG_TRI.add(2, ItemName.MANH_NHAN_JUMITO);
        TRANG_TRI.add(2, ItemName.MANH_PHU_JUMITO);
        TRANG_TRI.add(2, ItemName.MANH_DAY_CHUYEN_JUMITO);
        TRANG_TRI.add(10, ItemName.DA_CAP_6);
        TRANG_TRI.add(10, ItemName.DA_CAP_7);
        TRANG_TRI.add(10, ItemName.DA_CAP_8);
        TRANG_TRI.add(10, ItemName.DA_CAP_9);
        TRANG_TRI.add(10, ItemName.DA_CAP_10);
        TRANG_TRI.add(10, ItemName.DA_CAP_11);
        TRANG_TRI.add(7, ItemName.DAN_CHINH_XAC);
        TRANG_TRI.add(7, ItemName.DAN_HP);
        TRANG_TRI.add(7, ItemName.DAN_TAN_CONG);
        TRANG_TRI.add(7, ItemName.DAN_KHANG);
        TRANG_TRI.add(1, ItemName.BAT_BAO);
        TRANG_TRI.add(2, ItemName.CHIM_TINH_ANH);
        TRANG_TRI.add(0.50, ItemName.RUONG_BACH_NGAN);
        TRANG_TRI.add(0.25, ItemName.RUONG_HUYEN_BI);
        TRANG_TRI.add(3, ItemName.TUONG_LINH_THAO);
        TRANG_TRI.add(3, ItemName.HAC_NGUU);
        TRANG_TRI.add(3, ItemName.XICH_NHAN_NGAN_LANG);
        TRANG_TRI.add(2, ItemName.MAT_NA_ONNA_BUGEISHA);
        TRANG_TRI.add(2, ItemName.MAT_NA_SUPER_BROLY);
        TRANG_TRI.add(0.5, ItemName.BO_CAI_THIEN_GIAM_XOC);
        TRANG_TRI.add(0.5, ItemName.BO_CAI_THIEN_DANH_LUA);
        TRANG_TRI.add(0.5, ItemName.BO_CAI_THIEN_DONG_CO);
        TRANG_TRI.add(4, ItemName.HOAN_COT_CHI_CHU_TRUNG_CAP);
        TRANG_TRI.add(4, ItemName.HOAN_COT_CHI_CHU_CAO_CAP);
        TRANG_TRI.add(4, ItemName.HOAN_LUONG_CHI_THAO);
        TRANG_TRI.add(3, ItemName.TUI_VAI_CAP_3);
        TRANG_TRI.add(1, ItemName.HOA_TUYET);
        TRANG_TRI.add(1, ItemName.PHA_LE);
        TRANG_TRI.add(1, ItemName.NHAM_THACH);
        TRANG_TRI.add(2, ItemName.THUC_AN_7X);
        TRANG_TRI.add(1, ItemName.HAGGIS);
        TRANG_TRI.add(1, ItemName.GAY_TRAI_TIM);
        TRANG_TRI.add(1, ItemName.GAY_MAT_TRANG);
        TRANG_TRI.add(1, ItemName.HOAN_CHUYEN_TRUNG_CAP);
        TRANG_TRI.add(1, ItemName.HOAN_CHUYEN_SO_CAP);
        TRANG_TRI.add(0.5, ItemName.HARLEY_DAVIDSON);
        TRANG_TRI.add(0.5, ItemName.XE_MAY);
        TRANG_TRI.add(0.5, ItemName.NHAT_TU_LAM_PHONG);
        TRANG_TRI.add(0.5, ItemName.THIEN_NGUYET_CHI_NU);
        TRANG_TRI.add(0.5, ItemName.MAT_NA_SHIN_AH);
        TRANG_TRI.add(0.5, ItemName.MAT_NA_VO_DIEN);
        TRANG_TRI.add(0.5, ItemName.MAT_NA_ONI);
        TRANG_TRI.add(0.5, ItemName.MAT_NA_KUMA);
        TRANG_TRI.add(0.5, ItemName.MAT_NA_INU);
        TRANG_TRI.add(0.5, ItemName.HOA_KY_LAN);
        TRANG_TRI.add(0.5, ItemName.PHUONG_HOANG_NEW);
        TRANG_TRI.add(0.5, ItemName.AO_DAI_NAM);
        TRANG_TRI.add(0.5, ItemName.AO_DAI_NU);
        TRANG_TRI.add(0.01, ItemName.BUA_AITEMU);
        TRANG_TRI.add(0.01, ItemName.BUA_NORU);
        TRANG_TRI.add(0.01, ItemName.BUA_SOCHI);
        TRANG_TRI.add(0.01, ItemName.CHUYEN_TINH_THACH);
        TRANG_TRI.add(1, ItemName.BI_KIP_CUNG);
        TRANG_TRI.add(1, ItemName.BI_KIP_DAO);
        TRANG_TRI.add(1, ItemName.BI_KIP_KIEM_THUAT);
        TRANG_TRI.add(1, ItemName.BI_KIP_TIEU_THUAT);
        TRANG_TRI.add(1, ItemName.BI_KIP_QUAT);
        TRANG_TRI.add(1, ItemName.BI_KIP_KUNAI);
        TRANG_TRI.add(0.1, ItemName.HAKAIRO_YOROI);        
        //
        RANDOMFRUIT.add(44, ItemName.FALCON);
        RANDOMFRUIT.add(44, ItemName.BOMB);
        RANDOMFRUIT.add(44, ItemName.ROCKET);
        RANDOMFRUIT.add(30, ItemName.LOVE);
        RANDOMFRUIT.add(30, ItemName.RUBBER);
        RANDOMFRUIT.add(30, ItemName.SOUND);
        RANDOMFRUIT.add(30, ItemName.DIAMOND);
        RANDOMFRUIT.add(20, ItemName.PORTAL);
        RANDOMFRUIT.add(20, ItemName.SAND);
        RANDOMFRUIT.add(20, ItemName.GRAVITY);
        RANDOMFRUIT.add(20, ItemName.LIGHT);
        RANDOMFRUIT.add(20, ItemName.FLAME);
        RANDOMFRUIT.add(4, ItemName.RUMBLE);
        RANDOMFRUIT.add(4, ItemName.CONTROL);
        RANDOMFRUIT.add(4, ItemName.QUAKE);
        RANDOMFRUIT.add(4, ItemName.ICE);
        RANDOMFRUIT.add(4, ItemName.REVIVE);
        RANDOMFRUIT.add(4, ItemName.VENOM);
        RANDOMFRUIT.add(4, ItemName.SPIDER);
        RANDOMFRUIT.add(4, ItemName.DOUGHIN);
        RANDOMFRUIT.add(4, ItemName.MAGMA);
        RANDOMFRUIT.add(0.5, ItemName.KITSUNE);
        RANDOMFRUIT.add(0.5, ItemName.LEOPARD);
        RANDOMFRUIT.add(0.5, ItemName.DRAGON);
        RANDOMFRUIT.add(0.5, ItemName.SHADOW);
        RANDOMFRUIT.add(0.5, ItemName.SPIRIT);
        RANDOMFRUIT.add(0.5, ItemName.DARK);
        RANDOMFRUIT.add(0.5, ItemName.BLIZZARD);
        RANDOMFRUIT.add(0.5, ItemName.T_REX);
        RANDOMFRUIT.add(0.5, ItemName.MAMMOTH);
        //
        DIEU_GIAY.add(25, ItemName.DA_CAP_5);
        DIEU_GIAY.add(20, ItemName.DA_CAP_6);
        DIEU_GIAY.add(15, ItemName.DA_CAP_7);
        DIEU_GIAY.add(5, ItemName.THE_BAI_KINH_NGHIEM_GIA_TOC_SO);
        DIEU_GIAY.add(5, ItemName.THE_BAI_KINH_NGHIEM_GIA_TOC_TRUNG);
        DIEU_GIAY.add(4, ItemName.SASHIMI_CAO_CAP);
        DIEU_GIAY.add(4, ItemName.THUC_AN_6X);
        DIEU_GIAY.add(10, ItemName.DAN_CHINH_XAC);
        DIEU_GIAY.add(10, ItemName.DAN_HP);
        DIEU_GIAY.add(10, ItemName.DAN_TAN_CONG);
        DIEU_GIAY.add(10, ItemName.DAN_KHANG);
        DIEU_GIAY.add(5, ItemName.DOI_DEN);
        DIEU_GIAY.add(5, ItemName.HOA_TUYET);
        DIEU_GIAY.add(1, ItemName.BAT_BAO);
        DIEU_GIAY.add(4, ItemName.HAC_NGUU);
        DIEU_GIAY.add(5, ItemName.EXP_TRAU);
        DIEU_GIAY.add(4, ItemName.HOAN_COT_CHI_CHU_SO_CAP);
        DIEU_GIAY.add(4, ItemName.MAT_NA_VEGETA);
        DIEU_GIAY.add(4, ItemName.MAT_NA_KUNOICHI);
        DIEU_GIAY.add(5, ItemName.DA_DANH_VONG_CAP_1);
        DIEU_GIAY.add(5, ItemName.DA_DANH_VONG_CAP_2);
        DIEU_GIAY.add(10, ItemName.HOAN_LUONG_CHI_THAO);
        DIEU_GIAY.add(10, ItemName.HOAN_CHUYEN_SO_CAP);
        DIEU_GIAY.add(1, ItemName.PHA_LE);
        DIEU_GIAY.add(1, ItemName.NHAM_THACH);
        DIEU_GIAY.add(2, ItemName.UNG_LONG);
        ///
        DIEU_VAI.add(2, ItemName.MANH_AO_JIRAI);
        DIEU_VAI.add(2, ItemName.MANH_QUAN_JIRAI);
        DIEU_VAI.add(2, ItemName.MANH_GANG_TAY_JIRAI);
        DIEU_VAI.add(2, ItemName.MANH_GIAY_JIRAI);
        DIEU_VAI.add(2, ItemName.MANH_NON_JIRAI);
        DIEU_VAI.add(2, ItemName.MANH_NGOC_BOI_JIRAI);
        DIEU_VAI.add(2, ItemName.MANH_NHAN_JIRAI);
        DIEU_VAI.add(2, ItemName.MANH_PHU_JIRAI);
        DIEU_VAI.add(2, ItemName.MANH_DAY_CHUYEN_JIRAI);
        DIEU_VAI.add(2, ItemName.MANH_AO_JUMITO);
        DIEU_VAI.add(2, ItemName.MANH_QUAN_JUMITO);
        DIEU_VAI.add(2, ItemName.MANH_GANG_TAY_JUMITO);
        DIEU_VAI.add(2, ItemName.MANH_GIAY_JUMITO);
        DIEU_VAI.add(2, ItemName.MANH_NON_JUMITO);
        DIEU_VAI.add(2, ItemName.MANH_NGOC_BOI_JUMITO);
        DIEU_VAI.add(2, ItemName.MANH_NHAN_JUMITO);
        DIEU_VAI.add(2, ItemName.MANH_PHU_JUMITO);
        DIEU_VAI.add(2, ItemName.MANH_DAY_CHUYEN_JUMITO);
        DIEU_VAI.add(10, ItemName.DA_CAP_6);
        DIEU_VAI.add(10, ItemName.DA_CAP_7);
        DIEU_VAI.add(10, ItemName.DA_CAP_8);
        DIEU_VAI.add(10, ItemName.DA_CAP_9);
        DIEU_VAI.add(10, ItemName.DA_CAP_10);
        DIEU_VAI.add(10, ItemName.DA_CAP_11);
        DIEU_VAI.add(7, ItemName.DAN_CHINH_XAC);
        DIEU_VAI.add(7, ItemName.DAN_HP);
        DIEU_VAI.add(7, ItemName.DAN_TAN_CONG);
        DIEU_VAI.add(7, ItemName.DAN_KHANG);
        DIEU_VAI.add(1, ItemName.BAT_BAO);
        DIEU_VAI.add(2, ItemName.CHIM_TINH_ANH);
        DIEU_VAI.add(0.50, ItemName.RUONG_BACH_NGAN);
        DIEU_VAI.add(0.25, ItemName.RUONG_HUYEN_BI);
        DIEU_VAI.add(3, ItemName.TUONG_LINH_THAO);
        DIEU_VAI.add(3, ItemName.HAC_NGUU);
        DIEU_VAI.add(3, ItemName.XICH_NHAN_NGAN_LANG);
        DIEU_VAI.add(2, ItemName.MAT_NA_ONNA_BUGEISHA);
        DIEU_VAI.add(2, ItemName.MAT_NA_SUPER_BROLY);
        DIEU_VAI.add(0.5, ItemName.BO_CAI_THIEN_GIAM_XOC);
        DIEU_VAI.add(0.5, ItemName.BO_CAI_THIEN_DANH_LUA);
        DIEU_VAI.add(0.5, ItemName.BO_CAI_THIEN_DONG_CO);
        DIEU_VAI.add(4, ItemName.HOAN_COT_CHI_CHU_TRUNG_CAP);
        DIEU_VAI.add(4, ItemName.HOAN_COT_CHI_CHU_CAO_CAP);
        DIEU_VAI.add(4, ItemName.HOAN_LUONG_CHI_THAO);
        DIEU_VAI.add(3, ItemName.TUI_VAI_CAP_3);
        DIEU_VAI.add(1, ItemName.HOA_TUYET);
        DIEU_VAI.add(1, ItemName.PHA_LE);
        DIEU_VAI.add(1, ItemName.NHAM_THACH);
        DIEU_VAI.add(2, ItemName.THUC_AN_7X);
        DIEU_VAI.add(1, ItemName.HAGGIS);
        DIEU_VAI.add(1, ItemName.GAY_TRAI_TIM);
        DIEU_VAI.add(1, ItemName.GAY_MAT_TRANG);
        DIEU_VAI.add(1, ItemName.HOAN_CHUYEN_TRUNG_CAP);
        DIEU_VAI.add(1, ItemName.HOAN_CHUYEN_SO_CAP);
        DIEU_VAI.add(0.5, ItemName.HARLEY_DAVIDSON);
        DIEU_VAI.add(0.5, ItemName.XE_MAY);
        DIEU_VAI.add(0.5, ItemName.NHAT_TU_LAM_PHONG);
        DIEU_VAI.add(0.5, ItemName.THIEN_NGUYET_CHI_NU);
        DIEU_VAI.add(0.5, ItemName.MAT_NA_SHIN_AH);
        DIEU_VAI.add(0.5, ItemName.MAT_NA_VO_DIEN);
        DIEU_VAI.add(0.5, ItemName.MAT_NA_ONI);
        DIEU_VAI.add(0.5, ItemName.MAT_NA_KUMA);
        DIEU_VAI.add(0.5, ItemName.MAT_NA_INU);
        DIEU_VAI.add(0.5, ItemName.HOA_KY_LAN);
        DIEU_VAI.add(0.5, ItemName.PHUONG_HOANG_NEW);
        DIEU_VAI.add(0.5, ItemName.AO_DAI_NAM);
        DIEU_VAI.add(0.5, ItemName.AO_DAI_NU);
        DIEU_VAI.add(0.01, ItemName.BUA_AITEMU);
        DIEU_VAI.add(0.01, ItemName.BUA_NORU);
        DIEU_VAI.add(0.01, ItemName.BUA_SOCHI);
    }
}
